mm: memory: fix compilation after merge
commit 7bf1f5c

and move to mm/mmu_gather.c following commit d4199fa

../mm/memory.c:163:11: error: no member named 'page_size' in 'struct mmu_gather'
        if (tlb->page_size != 0 && tlb->page_size != PMD_SIZE)
            ~  ^                                   ~  ^
../mm/memory.c:166:7: error: no member named 'page_size' in 'struct mmu_gather'
        tlb->page_size = PMD_SIZE;
        ~~~  ^
requires this for fix 67ba1c2

Signed-off-by: Salllz <sal235222727@gmail.com>
Change-Id: Ida913dbe98e2cf8d2108f2dd5f0842b344518fb5